name: .NET Build

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]
    paths:
      - 'BackEnd/**'
      - '.github/workflows/**'

  push:
    branches: [ main ]
    paths:
      - 'BackEnd/**'
      - '.github/workflows/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (use PR/source branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Show projects in solution
        run: dotnet sln Jem_ID.sln list

      - name: Restore
        run: dotnet restore Jem_ID.sln
        working-directory: .

      - name: Build
        run: dotnet build Jem_ID.sln --no-restore -c Release
        working-directory: .
